moveit_cpp:
  planning_pipelines:
    - ompl
  pipeline_id: ompl

  ompl:
    planning_plugin: ompl_interface/OMPLPlanner
    request_adapters: default_planner_request_adapters/AddTimeParameterization
    start_state_max_bounds_error: 0.1