moveit_cpp:
  planning_pipelines:
    - chomp
  pipeline_id: chomp

  chomp:
    planning_plugin: chomp::ChompPlanner
    request_adapters: default_planner_request_adapters/AddTimeParameterization
    start_state_max_bounds_error: 0.1
